DELETE FROM Supervisor_Supervisee WHERE 1=1;
DELETE FROM Employees_On_Task WHERE 1=1;
DELETE FROM Task WHERE 1=1;
DELETE FROM Task_Status WHERE 1=1;
DELETE FROM Works_On WHERE 1=1;
DELETE FROM Project WHERE 1=1;
DELETE FROM Dept_Locations WHERE 1=1;
DELETE FROM Department WHERE 1=1;
DELETE FROM Location WHERE 1=1;
DELETE FROM Employee_Dependent WHERE 1=1;
DELETE FROM Dependent WHERE 1=1;
DELETE FROM Account WHERE 1=1;
DELETE FROM Employee WHERE 1=1;


