ALTER TABLE `Account`
  ADD CONSTRAINT `Account_ibfk_1` FOREIGN KEY (`Employee_id`) REFERENCES `Employee` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Department`
  ADD CONSTRAINT `Department_ibfk_1` FOREIGN KEY (`Mgr_id`) REFERENCES `Employee` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Dept_Locations`
  ADD CONSTRAINT `Dept_Locations_ibfk_1` FOREIGN KEY (`Dept_id`) REFERENCES `Department` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Dept_Locations_ibfk_2` FOREIGN KEY (`Location_id`) REFERENCES `Location` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Employee`
  ADD CONSTRAINT `Employee_ibfk_1` FOREIGN KEY (`Dept_id`) REFERENCES `Department` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Employees_On_Task`
  ADD CONSTRAINT `Employees_On_Task_ibfk_1` FOREIGN KEY (`Employee_id`) REFERENCES `Employee` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Employees_On_Task_ibfk_2` FOREIGN KEY (`Task_id`) REFERENCES `Task` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Employee_Dependent`
  ADD CONSTRAINT `Employee_Dependent_ibfk_1` FOREIGN KEY (`Employee_id`) REFERENCES `Employee` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Employee_Dependent_ibfk_2` FOREIGN KEY (`Dependent_id`) REFERENCES `Dependent` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Project`
  ADD CONSTRAINT `Project_ibfk_1` FOREIGN KEY (`Dept_id`) REFERENCES `Department` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Supervisor_Supervisee`
  ADD CONSTRAINT `Supervisor_Supervisee_ibfk_1` FOREIGN KEY (`Supervisor_id`) REFERENCES `Employee` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Supervisor_Supervisee_ibfk_2` FOREIGN KEY (`Supervisee_id`) REFERENCES `Employee` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Task`
  ADD CONSTRAINT `Task_ibfk_1` FOREIGN KEY (`Status`) REFERENCES `Task_Status` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Task_ibfk_2` FOREIGN KEY (`Proj_id`) REFERENCES `Project` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

ALTER TABLE `Works_On`
  ADD CONSTRAINT `Works_On_ibfk_1` FOREIGN KEY (`Employee_id`) REFERENCES `Employee` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Works_On_ibfk_2` FOREIGN KEY (`Proj_id`) REFERENCES `Project` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;